# Generated by Django 5.0.6 on 2026-07-14 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('content_uri', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalGate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_tier', models.IntegerField(default=4)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.court')),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.civilservantagent')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_members', to='agents.ship')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('validation_type', models.CharField(max_length=100)),
                ('passed', models.BooleanField(default=False)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='agents.artifact')),
            ],
        ),
        migrations.CreateModel(
            name='PullRequestRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pr_url', models.CharField(max_length=512)),
                ('status', models.CharField(default='Open', max_length=50)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.mission')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Open', max_length=50)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.crew')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='agents.mission')),
            ],
        ),
        migrations.AddField(
            model_name='artifact',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='agents.task'),
        ),
        migrations.CreateModel(
            name='WorkerLease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compute_resource_id', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.civilservantagent')),
            ],
        ),
    ]
