# Generated by Django 6.0.7 on 2026-07-14 22:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_artifact_objective_approvalgate_crew_evidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('event_hash', models.CharField(editable=False, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.civilservantagent')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorityGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_tier', models.IntegerField()),
                ('description', models.TextField()),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.civilservantagent')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('directive', models.TextField()),
                ('tier_requested', models.IntegerField(default=1)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.userpresident')),
            ],
        ),
        migrations.CreateModel(
            name='ConstitutionVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_hash', models.CharField(max_length=64, unique=True)),
                ('text', models.TextField()),
                ('enacted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DecisionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reasoning', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.task')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('worktree_path', models.CharField(max_length=512)),
                ('branch_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_runs', to='agents.task')),
            ],
        ),
        migrations.CreateModel(
            name='ModelInvocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('execution_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.executionrun')),
            ],
        ),
        migrations.RemoveField(
            model_name='audit',
            name='target_agency',
        ),
        migrations.DeleteModel(
            name='CensusReport',
        ),
        migrations.RemoveField(
            model_name='intelligencebrief',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='message',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='workerlease',
            name='agent',
        ),
        migrations.AddField(
            model_name='evidence',
            name='commit_sha',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='policy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pullrequestrecord',
            name='head_sha',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.command'),
        ),
        migrations.DeleteModel(
            name='Audit',
        ),
        migrations.DeleteModel(
            name='IntelligenceBrief',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='WorkerLease',
        ),
    ]
