"""The single Step-9 Magi tool: ``firstmate.submit_objective``.

The model supplies only a closed objective contract. Authenticated principal and
canonical conversation identities arrive separately from the route/service.
Submission adds one deterministic task to Firstmate's durable backlog and waits
only for that bounded queue acceptance; Firstmate owns all later orchestration.
No subprocess output or task transcript is returned to native chat.
"""
from __future__ import annotations

import asyncio
from dataclasses import dataclass
import hashlib
import json
import os
import re
import signal
import sqlite3
import stat as stat_module
import tempfile
import threading
import time
from typing import Any, Protocol, Sequence

from pydantic import BaseModel, ConfigDict, Field, ValidationError, field_validator, model_validator

from app import db
from app.firstmate_client import FirstmateClient
from app.magi_model import (
    MAGI_MAX_TOOL_ARGUMENT_BYTES,
    MagiModelToolCall,
    MagiToolDefinition,
    magi_text_has_unsafe_controls,
)
from app.magi_tool_protocol import (
    MagiToolContext,
    MagiToolError,
    MagiToolExecutionResult,
)

FIRSTMATE_SUBMIT_OBJECTIVE = "firstmate.submit_objective"
FIRSTMATE_OBJECTIVE_SCHEMA = "firstmate.objective.v1"
FIRSTMATE_OBJECTIVE_RESULT_SCHEMA = "firstmate.submit-objective-result.v1"
MAX_OBJECTIVE_CHARS = 4_000
MAX_PROJECT_CHARS = 160
MAX_OBJECTIVE_ITEMS = 16
MAX_OBJECTIVE_ITEM_CHARS = 1_000
MAX_CONTEXT_REFS = 16
MAX_CONTEXT_REF_CHARS = 256
MAX_OBJECTIVE_AGGREGATE_CHARS = 16_000
MAX_TASK_BODY_BYTES = 32 * 1024
MAX_TASKS_AXI_OUTPUT_BYTES = 64 * 1024
MAX_TASKS_AXI_STDERR_BYTES = 16 * 1024
TASKS_AXI_TIMEOUT_SECONDS = 10.0
_SAFE_PROJECT = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,159}$")
_SAFE_CONTEXT_REF = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._:/#-]{0,255}$")
_SAFE_CANONICAL_ID = re.compile(r"^(?:mgc|mgt|mgm)_[A-Za-z0-9_-]{4,124}$")
_SAFE_OWNER = re.compile(r"^[^\x00-\x1f\x7f-\x9f]{1,128}$")
_SAFE_INVOCATION_KEY = re.compile(r"^[0-9a-f]{64}$")
_SAFE_TASK_ID = re.compile(r"^magi-[0-9a-f]{32}$")
_SAFE_OBJECTIVE_ID = re.compile(r"^mgo_[0-9a-f]{32}$")
_SCHEMA_LOCK = threading.Lock()
_INITIALIZED_DB_PATHS: set[str] = set()


class FirstmateSubmitObjectiveContract(BaseModel):
    """Strict arguments generated by the model for one actionable objective."""

    model_config = ConfigDict(extra="forbid", strict=True)

    objective: str = Field(min_length=1, max_length=MAX_OBJECTIVE_CHARS)
    project: str = Field(min_length=1, max_length=MAX_PROJECT_CHARS, pattern=_SAFE_PROJECT.pattern)
    constraints: list[str] = Field(min_length=0, max_length=MAX_OBJECTIVE_ITEMS)
    acceptance_criteria: list[str] = Field(min_length=1, max_length=MAX_OBJECTIVE_ITEMS)
    context_refs: list[str] = Field(min_length=0, max_length=MAX_CONTEXT_REFS)

    @field_validator("objective")
    @classmethod
    def validate_objective(cls, value: str) -> str:
        return _bounded_contract_text(value, maximum=MAX_OBJECTIVE_CHARS)

    @field_validator("constraints", "acceptance_criteria")
    @classmethod
    def validate_items(cls, values: list[str]) -> list[str]:
        checked = [
            _bounded_contract_text(value, maximum=MAX_OBJECTIVE_ITEM_CHARS)
            for value in values
        ]
        if len(set(checked)) != len(checked):
            raise ValueError("Objective list entries must be unique.")
        return checked

    @field_validator("context_refs")
    @classmethod
    def validate_context_refs(cls, values: list[str]) -> list[str]:
        if any(not isinstance(value, str) or not _SAFE_CONTEXT_REF.fullmatch(value) for value in values):
            raise ValueError("Objective context references must be bounded opaque identifiers.")
        if len(set(values)) != len(values):
            raise ValueError("Objective context references must be unique.")
        return values

    @model_validator(mode="after")
    def validate_aggregate_bounds(self) -> "FirstmateSubmitObjectiveContract":
        aggregate = (
            len(self.objective) + len(self.project)
            + sum(map(len, self.constraints))
            + sum(map(len, self.acceptance_criteria))
            + sum(map(len, self.context_refs))
        )
        if aggregate > MAX_OBJECTIVE_AGGREGATE_CHARS:
            raise ValueError("Objective arguments exceed the aggregate text bound.")
        encoded = _canonical_json(self.model_dump(mode="json")).encode("utf-8", errors="strict")
        if len(encoded) > MAGI_MAX_TOOL_ARGUMENT_BYTES:
            raise ValueError("Objective arguments exceed the encoded contract bound.")
        return self


def _bounded_contract_text(value: Any, *, maximum: int) -> str:
    if (
        not isinstance(value, str)
        or not value or value != value.strip()
        or len(value) > maximum
        or magi_text_has_unsafe_controls(value)
    ):
        raise ValueError("Objective text must be non-blank, bounded, and control-free.")
    try:
        value.encode("utf-8", errors="strict")
    except UnicodeEncodeError as exc:
        raise ValueError("Objective text must contain valid Unicode scalar values.") from exc
    return value


def _canonical_json(value: Any) -> str:
    return json.dumps(
        value, ensure_ascii=False, separators=(",", ":"), sort_keys=True, allow_nan=False,
    )


def _strict_object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("Objective arguments contain duplicate JSON keys.")
        result[key] = value
    return result


def _reject_json_constant(_: str) -> None:
    raise ValueError("Objective arguments contain a non-finite number.")


def parse_submit_objective_arguments(arguments_json: str) -> FirstmateSubmitObjectiveContract:
    """Decode raw provider arguments without accepting aliases or duplicate keys."""
    if not isinstance(arguments_json, str) or not arguments_json.strip():
        raise MagiToolError("objective_arguments_invalid", retryable=False)
    try:
        encoded = arguments_json.encode("utf-8", errors="strict")
    except UnicodeEncodeError as exc:
        raise MagiToolError("objective_arguments_invalid", retryable=False) from exc
    if len(encoded) > MAGI_MAX_TOOL_ARGUMENT_BYTES or magi_text_has_unsafe_controls(arguments_json):
        raise MagiToolError("objective_arguments_invalid", retryable=False)
    try:
        value = json.loads(
            arguments_json,
            object_pairs_hook=_strict_object,
            parse_constant=_reject_json_constant,
        )
        if not isinstance(value, dict):
            raise ValueError("Objective arguments must be an object.")
        return FirstmateSubmitObjectiveContract.model_validate(value)
    except (ValueError, TypeError, ValidationError, json.JSONDecodeError, RecursionError) as exc:
        raise MagiToolError("objective_arguments_invalid", retryable=False) from exc


SUBMIT_OBJECTIVE_PARAMETERS: dict[str, Any] = {
    "type": "object",
    "additionalProperties": False,
    "properties": {
        # OpenAI strict tools support a deliberately small JSON Schema subset.
        # Bounds and patterns are still mandatory, but the host enforces them
        # after decoding rather than relying on provider-specific keywords.
        "objective": {
            "type": "string",
            "description": "A non-blank concrete engineering outcome, at most 4000 characters.",
        },
        "project": {
            "type": "string",
            "description": "The configured project/repository slug, such as Magistrate.",
        },
        "constraints": {
            "type": "array",
            "items": {"type": "string"},
            "description": "At most 16 constraints stated or necessarily implied by the user and current context.",
        },
        "acceptance_criteria": {
            "type": "array",
            "items": {"type": "string"},
            "description": "One to 16 observable criteria that would verify the requested outcome.",
        },
        "context_refs": {
            "type": "array",
            "items": {"type": "string"},
            "description": "At most 16 bounded opaque authenticated-context ids; never raw context text.",
        },
    },
    "required": [
        "objective", "project", "constraints", "acceptance_criteria", "context_refs",
    ],
}

SUBMIT_OBJECTIVE_DEFINITION = MagiToolDefinition(
    name=FIRSTMATE_SUBMIT_OBJECTIVE,
    description=(
        "Submit exactly one actionable engineering objective for asynchronous execution. "
        "Use this only when the user asks Magi to change, build, fix, test, investigate, "
        "or ship project work. Do not use it for questions, explanations, brainstorming, "
        "or ordinary conversation. Existing authorization and confirmation policy still applies."
    ),
    parameters=SUBMIT_OBJECTIVE_PARAMETERS,
)


@dataclass(frozen=True)
class ObjectiveClaim:
    objective_id: str
    task_id: str
    contract_json: str
    contract_sha256: str
    accepted: bool
    duplicate: bool
    attempt: int


@dataclass(frozen=True)
class ObjectiveDispatchReceipt:
    already_present: bool


class ObjectiveDispatchError(RuntimeError):
    pass


class ObjectiveDispatcher(Protocol):
    async def submit(
        self,
        *,
        task_id: str,
        title: str,
        project: str,
        body: str,
    ) -> ObjectiveDispatchReceipt:
        ...


def _now_ms() -> int:
    return int(time.time_ns() // 1_000_000)


def _connect_objectives() -> sqlite3.Connection:
    path = str(db.DB_PATH)
    if path not in _INITIALIZED_DB_PATHS:
        with _SCHEMA_LOCK:
            if path not in _INITIALIZED_DB_PATHS:
                db.init_db()
                connection = sqlite3.connect(db.DB_PATH, timeout=10)
                try:
                    connection.execute("PRAGMA foreign_keys = ON")
                    connection.execute(
                        """CREATE TABLE IF NOT EXISTS magi_objective_submissions (
                               objective_id TEXT PRIMARY KEY,
                               task_id TEXT NOT NULL UNIQUE,
                               owner_user_id TEXT NOT NULL,
                               invocation_key TEXT NOT NULL,
                               conversation_id TEXT NOT NULL,
                               turn_id TEXT NOT NULL,
                               user_message_id TEXT NOT NULL,
                               assistant_message_id TEXT NOT NULL,
                               contract_json TEXT NOT NULL,
                               contract_sha256 TEXT NOT NULL,
                               status TEXT NOT NULL CHECK(status IN ('submitting','accepted','failed')),
                               attempt_count INTEGER NOT NULL DEFAULT 1,
                               last_error_code TEXT,
                               accepted_at INTEGER,
                               created_at INTEGER NOT NULL,
                               updated_at INTEGER NOT NULL,
                               UNIQUE(owner_user_id, invocation_key)
                           )"""
                    )
                    connection.execute(
                        """CREATE INDEX IF NOT EXISTS idx_magi_objectives_owner_task
                           ON magi_objective_submissions(owner_user_id, task_id)"""
                    )
                    connection.execute(
                        """CREATE INDEX IF NOT EXISTS idx_magi_objectives_chat_turn
                           ON magi_objective_submissions(owner_user_id, conversation_id, turn_id)"""
                    )
                    connection.commit()
                finally:
                    connection.close()
                _INITIALIZED_DB_PATHS.add(path)
    connection = sqlite3.connect(db.DB_PATH, timeout=10)
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA foreign_keys = ON")
    return connection


def _validate_context(context: MagiToolContext) -> None:
    if (
        not isinstance(context, MagiToolContext)
        or context.command_authorized is not True
        or not isinstance(context.owner_user_id, str)
        or not _SAFE_OWNER.fullmatch(context.owner_user_id)
        or any(
            not isinstance(value, str) or not _SAFE_CANONICAL_ID.fullmatch(value)
            for value in (
                context.conversation_id, context.turn_id, context.user_message_id,
                context.assistant_message_id,
            )
        )
    ):
        raise MagiToolError("objective_not_authorized", retryable=False)


class ObjectiveSubmissionStore:
    """Principal-qualified idempotency ledger for Firstmate queue acceptance."""

    @staticmethod
    def _identities(owner_user_id: str, invocation_key: str) -> tuple[str, str]:
        digest = hashlib.sha256(
            f"magi-objective-v1\0{owner_user_id}\0{invocation_key}".encode("utf-8")
        ).hexdigest()
        return f"mgo_{digest[:32]}", f"magi-{digest[32:64]}"

    def claim(
        self,
        *,
        context: MagiToolContext,
        invocation_key: str,
        contract: FirstmateSubmitObjectiveContract,
    ) -> ObjectiveClaim:
        _validate_context(context)
        if not isinstance(invocation_key, str) or not _SAFE_INVOCATION_KEY.fullmatch(invocation_key):
            raise MagiToolError("objective_idempotency_invalid", retryable=False)
        contract_json = _canonical_json(contract.model_dump(mode="json"))
        contract_sha256 = hashlib.sha256(contract_json.encode("utf-8")).hexdigest()
        objective_id, task_id = self._identities(context.owner_user_id, invocation_key)
        now = _now_ms()
        connection = _connect_objectives()
        try:
            connection.execute("BEGIN IMMEDIATE")
            existing = connection.execute(
                """SELECT * FROM magi_objective_submissions
                   WHERE owner_user_id = ? AND invocation_key = ?""",
                (context.owner_user_id, invocation_key),
            ).fetchone()
            if existing is not None:
                immutable = (
                    existing["objective_id"], existing["task_id"], existing["conversation_id"],
                    existing["turn_id"], existing["user_message_id"],
                    existing["assistant_message_id"], existing["contract_sha256"],
                    existing["contract_json"],
                )
                expected = (
                    objective_id, task_id, context.conversation_id, context.turn_id,
                    context.user_message_id, context.assistant_message_id,
                    contract_sha256, contract_json,
                )
                if immutable != expected:
                    raise MagiToolError("objective_idempotency_conflict", retryable=False)
                if existing["status"] == "accepted":
                    connection.commit()
                    return ObjectiveClaim(
                        objective_id, task_id, contract_json, contract_sha256,
                        accepted=True, duplicate=True, attempt=int(existing["attempt_count"]),
                    )
                attempt = int(existing["attempt_count"]) + 1
                connection.execute(
                    """UPDATE magi_objective_submissions
                       SET status = 'submitting', attempt_count = ?, last_error_code = NULL,
                           updated_at = ? WHERE objective_id = ? AND owner_user_id = ?""",
                    (attempt, now, objective_id, context.owner_user_id),
                )
                connection.commit()
                return ObjectiveClaim(
                    objective_id, task_id, contract_json, contract_sha256,
                    accepted=False, duplicate=True, attempt=attempt,
                )
            connection.execute(
                """INSERT INTO magi_objective_submissions
                   (objective_id, task_id, owner_user_id, invocation_key, conversation_id,
                    turn_id, user_message_id, assistant_message_id, contract_json,
                    contract_sha256, status, attempt_count, created_at, updated_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'submitting', 1, ?, ?)""",
                (
                    objective_id, task_id, context.owner_user_id, invocation_key,
                    context.conversation_id, context.turn_id, context.user_message_id,
                    context.assistant_message_id, contract_json, contract_sha256, now, now,
                ),
            )
            connection.commit()
            return ObjectiveClaim(
                objective_id, task_id, contract_json, contract_sha256,
                accepted=False, duplicate=False, attempt=1,
            )
        except MagiToolError:
            connection.rollback()
            raise
        except (sqlite3.Error, ValueError, UnicodeError) as exc:
            connection.rollback()
            raise MagiToolError("objective_store_unavailable") from exc
        finally:
            connection.close()

    def accept(self, owner_user_id: str, claim: ObjectiveClaim) -> None:
        now = _now_ms()
        connection = _connect_objectives()
        try:
            connection.execute("BEGIN IMMEDIATE")
            changed = connection.execute(
                """UPDATE magi_objective_submissions
                   SET status = 'accepted', last_error_code = NULL, accepted_at = COALESCE(accepted_at, ?),
                       updated_at = ?
                   WHERE objective_id = ? AND owner_user_id = ? AND contract_sha256 = ?""",
                (now, now, claim.objective_id, owner_user_id, claim.contract_sha256),
            ).rowcount
            if changed != 1:
                raise MagiToolError("objective_store_conflict", retryable=False)
            connection.commit()
        except MagiToolError:
            connection.rollback()
            raise
        except sqlite3.Error as exc:
            connection.rollback()
            raise MagiToolError("objective_store_unavailable") from exc
        finally:
            connection.close()

    def fail(self, owner_user_id: str, claim: ObjectiveClaim, code: str) -> None:
        safe_code = code if re.fullmatch(r"[a-z0-9][a-z0-9._-]{0,63}", code or "") else "objective_dispatch_failed"
        connection: sqlite3.Connection | None = None
        try:
            connection = _connect_objectives()
            connection.execute(
                """UPDATE magi_objective_submissions
                   SET status = 'failed', last_error_code = ?, updated_at = ?
                   WHERE objective_id = ? AND owner_user_id = ? AND status != 'accepted'""",
                (safe_code, _now_ms(), claim.objective_id, owner_user_id),
            )
            connection.commit()
        except sqlite3.Error:
            # The original safe dispatch error remains authoritative. Never
            # replace it with exception text from best-effort failure recording.
            return
        finally:
            if connection is not None:
                connection.close()

    def get(self, owner_user_id: str, objective_id: str) -> dict[str, Any] | None:
        if (
            not isinstance(owner_user_id, str) or not _SAFE_OWNER.fullmatch(owner_user_id)
            or not isinstance(objective_id, str) or not _SAFE_OBJECTIVE_ID.fullmatch(objective_id)
        ):
            return None
        connection = _connect_objectives()
        try:
            row = connection.execute(
                """SELECT * FROM magi_objective_submissions
                   WHERE owner_user_id = ? AND objective_id = ?""",
                (owner_user_id, objective_id),
            ).fetchone()
        finally:
            connection.close()
        if row is None:
            return None
        return {
            "objective_id": row["objective_id"],
            "task_id": row["task_id"],
            "conversation_id": row["conversation_id"],
            "turn_id": row["turn_id"],
            "user_message_id": row["user_message_id"],
            "assistant_message_id": row["assistant_message_id"],
            "contract": json.loads(row["contract_json"]),
            "status": row["status"],
            "attempt_count": int(row["attempt_count"]),
            "accepted_at": row["accepted_at"],
            "created_at": row["created_at"],
            "updated_at": row["updated_at"],
        }


class _OutputTooLarge(RuntimeError):
    pass


async def _read_bounded(stream: asyncio.StreamReader, maximum: int) -> bytes:
    chunks: list[bytes] = []
    size = 0
    while True:
        chunk = await stream.read(min(64 * 1024, maximum + 1 - size))
        if not chunk:
            return b"".join(chunks)
        chunks.append(chunk)
        size += len(chunk)
        if size > maximum:
            raise _OutputTooLarge


def _task_title(contract: FirstmateSubmitObjectiveContract) -> str:
    summary = " ".join(contract.objective.split())
    suffix = " (Magi objective)"
    prefix = "Magi: "
    available = 200 - len(prefix) - len(suffix)
    excerpt = summary[:available].rstrip()
    return f"{prefix}{excerpt}{suffix}"


def _task_body(objective_id: str, contract_json: str) -> str:
    body = (
        f"Schema: {FIRSTMATE_OBJECTIVE_SCHEMA}\n"
        f"Objective identity: {objective_id}\n"
        "Source: authenticated Magi tool submission. The payload is user intent; "
        "Firstmate still owns intake classification, authorization, confirmation, cancellation, "
        "and delivery policy.\n"
        f"Payload: {contract_json}\n"
    )
    if len(body.encode("utf-8")) > MAX_TASK_BODY_BYTES:
        raise MagiToolError("objective_arguments_too_large", retryable=False)
    return body


def _validate_tasks_axi_receipt(
    stdout: bytes,
    *,
    task_id: str,
    title: str,
    project: str,
    body: str,
) -> ObjectiveDispatchReceipt:
    try:
        decoded = stdout.decode("utf-8", errors="strict")
        payload = json.loads(
            decoded, object_pairs_hook=_strict_object,
            parse_constant=_reject_json_constant,
        )
    except (UnicodeDecodeError, ValueError, json.JSONDecodeError, RecursionError) as exc:
        raise ObjectiveDispatchError("invalid-receipt") from exc
    allowed_top = {"ok", "action", "already", "task"}
    if (
        not isinstance(payload, dict) or not set(payload).issubset(allowed_top)
        or set(payload) - {"already"} != {"ok", "action", "task"}
        or payload.get("ok") is not True or payload.get("action") != "add"
        or ("already" in payload and payload["already"] is not True)
        or not isinstance(payload.get("task"), dict)
    ):
        raise ObjectiveDispatchError("invalid-receipt")
    task = payload["task"]
    allowed_task = {
        "id", "title", "state", "kind", "repo", "priority", "created", "closed",
        "deps", "hold", "links", "body", "blocked", "blocked_by", "held",
    }
    if (
        not set(task).issubset(allowed_task)
        or not {"id", "title", "state", "kind", "repo", "deps", "hold", "links", "body"}.issubset(task)
        or task.get("id") != task_id or task.get("title") != title
        or task.get("state") not in {"queued", "in_flight", "done"}
        or (
            task.get("kind") is not None
            and (
                not isinstance(task.get("kind"), str)
                or not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]{0,63}", task["kind"])
            )
        )
        or task.get("repo") != project
        or task.get("body") != body
        or not isinstance(task.get("deps"), list)
        or not isinstance(task.get("links"), list)
        or task.get("hold") is not None and not isinstance(task.get("hold"), dict)
        or "blocked" in task and type(task["blocked"]) is not bool
        or "held" in task and type(task["held"]) is not bool
        or "blocked_by" in task and not isinstance(task["blocked_by"], list)
    ):
        raise ObjectiveDispatchError("invalid-receipt")
    return ObjectiveDispatchReceipt(already_present=payload.get("already") is True)


class TasksAxiObjectiveDispatcher:
    """Bounded structured write into Firstmate's existing backlog authority."""

    def __init__(
        self,
        firstmate: FirstmateClient | None = None,
        *,
        timeout_seconds: float = TASKS_AXI_TIMEOUT_SECONDS,
    ) -> None:
        self._firstmate = firstmate
        self._timeout_seconds = timeout_seconds

    async def submit(
        self,
        *,
        task_id: str,
        title: str,
        project: str,
        body: str,
    ) -> ObjectiveDispatchReceipt:
        if (
            not _SAFE_TASK_ID.fullmatch(task_id)
            or not title or "\n" in title or "\r" in title or len(title) > 200
            or not _SAFE_PROJECT.fullmatch(project)
            or not body or len(body.encode("utf-8")) > MAX_TASK_BODY_BYTES
        ):
            raise ObjectiveDispatchError("invalid-request")
        firstmate = self._firstmate or FirstmateClient()
        tool_path = firstmate.get_trusted_tool_path()
        runtime_home = firstmate.get_trusted_runtime_home()
        fm_home = firstmate.fm_home
        try:
            home_stat = os.lstat(fm_home)
        except OSError as exc:
            raise ObjectiveDispatchError("runtime-unavailable") from exc
        if (
            tool_path is None or runtime_home is None
            or not stat_module.S_ISDIR(home_stat.st_mode)
            or stat_module.S_ISLNK(home_stat.st_mode)
            or home_stat.st_uid != os.geteuid()
        ):
            raise ObjectiveDispatchError("runtime-unavailable")
        environment = {
            "FM_HOME": fm_home,
            "PATH": tool_path,
            "HOME": runtime_home,
            "LANG": "C.UTF-8",
            "LC_ALL": "C.UTF-8",
            "NO_COLOR": "1",
        }
        descriptor = -1
        body_path = ""
        process: asyncio.subprocess.Process | None = None
        try:
            descriptor, body_path = tempfile.mkstemp(prefix="magistrate-objective-", text=False)
            os.fchmod(descriptor, 0o600)
            with os.fdopen(descriptor, "wb") as stream:
                descriptor = -1
                stream.write(body.encode("utf-8", errors="strict"))
            process = await asyncio.create_subprocess_exec(
                "tasks-axi", "add", task_id, title,
                "--repo", project,
                "--body-file", body_path, "--queue", "--json",
                stdin=asyncio.subprocess.DEVNULL,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                cwd=fm_home,
                env=environment,
                start_new_session=True,
            )

            async def collect() -> tuple[bytes, bytes, int]:
                stdout, stderr, return_code = await asyncio.gather(
                    _read_bounded(process.stdout, MAX_TASKS_AXI_OUTPUT_BYTES),
                    _read_bounded(process.stderr, MAX_TASKS_AXI_STDERR_BYTES),
                    process.wait(),
                )
                return stdout, stderr, return_code

            try:
                stdout, stderr, return_code = await asyncio.wait_for(
                    collect(), timeout=self._timeout_seconds,
                )
            except (asyncio.TimeoutError, _OutputTooLarge) as exc:
                try:
                    os.killpg(process.pid, signal.SIGKILL)
                except ProcessLookupError:
                    pass
                await process.wait()
                raise ObjectiveDispatchError("runtime-bound-exceeded") from exc
            if return_code != 0 or stderr:
                raise ObjectiveDispatchError("submission-refused")
            return _validate_tasks_axi_receipt(
                stdout, task_id=task_id, title=title, project=project, body=body,
            )
        except asyncio.CancelledError:
            if process is not None and process.returncode is None:
                try:
                    os.killpg(process.pid, signal.SIGKILL)
                except ProcessLookupError:
                    pass
                await process.wait()
            raise
        except ObjectiveDispatchError:
            raise
        except (OSError, UnicodeError, ValueError) as exc:
            if process is not None and process.returncode is None:
                try:
                    os.killpg(process.pid, signal.SIGKILL)
                except ProcessLookupError:
                    pass
                await process.wait()
            raise ObjectiveDispatchError("runtime-unavailable") from exc
        finally:
            if descriptor >= 0:
                os.close(descriptor)
            if body_path:
                try:
                    os.unlink(body_path)
                except OSError:
                    pass


class FirstmateObjectiveTools:
    """Closed one-tool registry for Native Chat Step 9."""

    def __init__(
        self,
        *,
        store: ObjectiveSubmissionStore | None = None,
        dispatcher: ObjectiveDispatcher | None = None,
    ) -> None:
        self.store = store or ObjectiveSubmissionStore()
        self.dispatcher = dispatcher or TasksAxiObjectiveDispatcher()

    @property
    def definitions(self) -> Sequence[MagiToolDefinition]:
        return (SUBMIT_OBJECTIVE_DEFINITION,)

    async def execute(
        self,
        call: MagiModelToolCall,
        *,
        context: MagiToolContext,
        invocation_key: str,
    ) -> MagiToolExecutionResult:
        _validate_context(context)
        if not isinstance(call, MagiModelToolCall) or call.name != FIRSTMATE_SUBMIT_OBJECTIVE:
            raise MagiToolError("tool_not_supported", retryable=False)
        contract = parse_submit_objective_arguments(call.arguments_json)
        claim = self.store.claim(
            context=context, invocation_key=invocation_key, contract=contract,
        )
        if not claim.accepted:
            title = _task_title(contract)
            body = _task_body(claim.objective_id, claim.contract_json)
            try:
                await self.dispatcher.submit(
                    task_id=claim.task_id,
                    title=title,
                    project=contract.project,
                    body=body,
                )
            except asyncio.CancelledError:
                # The deterministic task identity makes a later retry safe even
                # if cancellation raced the external command's atomic publish.
                raise
            except ObjectiveDispatchError as exc:
                self.store.fail(context.owner_user_id, claim, "objective_dispatch_failed")
                raise MagiToolError("objective_dispatch_failed") from exc
            self.store.accept(context.owner_user_id, claim)
        return MagiToolExecutionResult(payload={
            "schema_version": FIRSTMATE_OBJECTIVE_RESULT_SCHEMA,
            "status": "accepted",
            "objective_id": claim.objective_id,
            "task_id": claim.task_id,
        })
